### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [sdex/ActivityManager#14]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 06 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on ActivityManager (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve ActivityManager's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by sdex** [comment]
It's interesting because the app doesn't use any cryptography. 
Please use activitymanagerapp@gmail.com for the correspondence.
