### ISSUE TITLE
Check duplicate history items

### ISSUE THREAD

**Issue by wh201906** [sdex/ActivityManager#17]
Hi. 
In the current version, `addToHistory()` will not check if the history item with the same parameters already exists in the history. IMO this app will be more convenient if the exactly same history items will be shown only once. Making this feature optional is also great.
Some users, including me, treat the history as an alternative to shortcut. In this case, we don't need to record what parameters are used each time, we just need to record the parameters themselves. Maybe you could delete the existing one when adding an item. 
Anyway, thank you for this amazing tool!

**Comment by sdex** [comment]
Hello. 
History is meant to store all records, in spite of parameters, it's more like logging.
The best I can offer is adding a check box to the bottom of the screen and if it's unchecked the new record won't be saved.

**Comment by wh201906** [comment]
It will be also great if you can do so. Thanks.
