### ISSUE TITLE
Closing an application bottom sheet menu cancels the current search

### ISSUE THREAD

**Issue by sdex** [sdex/ActivityManager#18]
Steps to reproduce: 
1. Search for any text
2. Open an application bottom sheet menu
3. Close the menu using the back button and touch the outside of it
4. The search is canceled

**Comment by sdex** [comment]
The androidx fragment issue to track:
https://issuetracker.google.com/issues/244336571

**Comment by drogga** [comment]
So it can be closed now?

**Comment by sdex** [comment]
Not really. I had to downgrade the library version to avoid some undesired behavior but this way has no future. The bug should be fixed in the fragments library. So this issue will be open until then.

**Comment by sdex** [comment]
[Fixed](https://issuetracker.google.com/issues/244336571#comment20) in `androidx.fragment:fragment:1.5.6` and in Activity Manager 5.3.3.
