### ISSUE TITLE
App becomes unresponsive when opening manifest viewer

### ISSUE THREAD

**Issue by notpeelz** [sdex/ActivityManager#19]
When I open the manifest viewer, the app becomes unresponsive for several seconds, sometimes even several minutes if the manifest is really big. The initial render seems to display the manifest just fine but I can't scroll at all and usually get the "Activity Manager isn't responding" prompt.

Android version: 11
Activity Manager version: 5.2.1
Tested with these packages:
- Firefox Nightly (`org.mozilla.fenix`: hangs for ~25-30s
- Google Photos (`com.google.android.apps.photos`):  had to kill the app after a couple minutes

**Comment by sdex** [comment]
It's hard to say unequivocally what is the cause of the ANR. The most likely root cause is the system webview your device uses. 
If you can, please share the traces file as described [here](https://developer.android.com/topic/performance/vitals/anr#trace-files), it might help to pinpoint the issue cause. 

I tested the app with much bigger manifests though. For instance, airbnb app:

![photo1670055764](https://user-images.githubusercontent.com/3196011/205431823-a702e17f-914c-41ef-83c4-867e74b2e811.jpeg)

**Comment by notpeelz** [comment]
[anr_2022-12-03-15-20-34-751.zip](https://github.com/sdex/ActivityManager/files/10147340/anr_2022-12-03-15-20-34-751.zip)

Note that my phone is rooted, not sure if it could interfere with the webview.
Custom ROM: LineageOS 18.1 (20220519-NIGHTLY-kebab)
Magisk: 25.2 (with Zygisk)
I also tried disabling most of my Magisk modules, but it didn't change anything.

**Comment by sdex** [comment]
Thanks for the detailed report!
I've updated the highlightjs library in #20. Could you check it? 
I see that you already build the app from the source code, so I suppose it won't be a problem.

**Comment by notpeelz** [comment]
The problem doesn't seem to be JavaScript-related. I apologize if I mislead you.
I only switched to an unminified version of hljs so it would be easier to see if the JavaScript code was causing the ANR.

Here's a video that demonstrates the issue better: https://i.imgur.com/hLXeWjw.mp4
(recorded on 8a1c9b3bf6840abfbe0daed965c67143a425e607)

Like you mentioned earlier, I'm thinking this is a bug with my phone's WebView (`/product/app/webview/webview.apk`). Is this something that Google can fix via a Play Store update, or would I have to update my Android install?

**Comment by sdex** [comment]
Great, thanks for the update!

FYI, there is [the magisk module](https://github.com/Androidacy/WebviewManager-Module) to change the system WebView.
