### ISSUE TITLE
Improve searching in manifest files

### ISSUE THREAD

**Issue by sdex** [sdex/ActivityManager#21]
**Add s search bar similar to browsers.** 

Firefox (at the bottom): 
![photo1670579128](https://user-images.githubusercontent.com/3196011/206673932-4c2ee82f-9677-4f39-bddf-462a7500bde4.jpeg)

Chrome (at the top):
![photo1670579131](https://user-images.githubusercontent.com/3196011/206674084-af282e0c-300e-4202-8e4d-84c7028a7322.jpeg)

**Comment by Y-E-P** [comment]
I'm on it right now. Assign it to me please.

**Comment by sdex** [comment]
Added in #37
