### ISSUE TITLE
Manifest view refreshes after rotating device

### ISSUE THREAD

**Issue by mmc20520** [sdex/ActivityManager#3]
Open a manifest file and scroll to a random position. Rotate screen and you will find the page scroll back to top. Then I need to manually restore the position.

Before rotation:
<img width="287" alt="Screen Shot 2022-03-04 at 8 17 11 PM" src="https://user-images.githubusercontent.com/100833575/156762076-4d757b37-2fa8-41f9-bef8-2ad072c2ee69.png">

After rotation:
<img width="629" alt="Screen Shot 2022-03-04 at 8 17 19 PM" src="https://user-images.githubusercontent.com/100833575/156762098-18e8ffc7-dfe7-45b7-8fe9-6232372d0bf2.png">

I was testing on v4.1.4 on Android 10

**Comment by sdex** [comment]
Fixed in #10
