### ISSUE TITLE
How I can access "Running services" in "Developer options" activity?

### ISSUE THREAD

**Issue by hamedsbt** [sdex/ActivityManager#31]
How I can access in "Developer options" -> "Running services" activity?

![Screenshot_20230308-000137_Settings](https://user-images.githubusercontent.com/7298328/223545606-650218f6-995b-4fe6-a827-da5a7c09e267.png)

**Comment by sdex** [comment]
You need to dig into the Settings app [source code](https://android.googlesource.com/platform/packages/apps/Settings/). The `SettingsActivity` class accepts the [EXTRA_SHOW_FRAGMENT](https://android.googlesource.com/platform/packages/apps/Settings/+/master/src/com/android/settings/SettingsActivity.java#104) argument, where you can specify the fragment name. Maybe there is a fragment or an action to open the list you need.

**Comment by Galbert01** [comment]
Hey can you redo my whole font back to factory no extension or data that's
saved on my accounts but passwords photos screenshots docs  and calender is
all I want  because it's like my phone got copied to another device and now
I'm felling like my device has been hacked please help

**Comment by hamedsbt** [comment]
> You need to dig into the Settings app [source code](https://android.googlesource.com/platform/packages/apps/Settings/). The `SettingsActivity` class accepts the [EXTRA_SHOW_FRAGMENT](https://android.googlesource.com/platform/packages/apps/Settings/+/master/src/com/android/settings/SettingsActivity.java#104) argument, where you can specify the fragment name. Maybe there is a fragment or an action to open the list you need.

I'm not professional Android user, I use shell command: ```dumpsys activity activities | grep mResumedActivity``` while _Developer options/Running services_ is running and result is: ```mResumedActivity: ActivityRecord{9306f2e u0 com.android.settings/.SubSettings t1550}``` So could you help me more to use it please? Thank you!
