### ISSUE TITLE
Shortcut not working "App isn't installed"

### ISSUE THREAD

**Issue by dimenfer** [sdex/ActivityManager#32]
Using OneUI 5.1 on Galaxy S21

I made a shortcut for "com.android.settings.notification.history.NotificationHistoryActivity" inside "com.android.settings", but when I tried to open the shortcut, a toast message says "App isn't installed", but if I try to open directly form the list (in Activity Manager) it opens normally.

**Comment by sdex** [comment]
Thank you for reporting this! I'm working on the fix.

**Comment by sdex** [comment]
Fixed in [5.3.4](https://github.com/sdex/ActivityManager/releases/tag/5.3.4)
