### ISSUE TITLE
Similar to #3, Notices scroll position also gets lost after device rotation

### ISSUE THREAD

**Issue by mmc20520** [sdex/ActivityManager#4]
Similar to #3, Notices scroll position also gets lost after device rotation

Before rotation:
<img width="289" alt="Screen Shot 2022-03-06 at 5 13 06 PM" src="https://user-images.githubusercontent.com/100833575/156916727-4e4665a9-6c95-4f4c-8362-1ffb239b0201.png">

After rotation:

<img width="602" alt="Screen Shot 2022-03-06 at 5 13 17 PM" src="https://user-images.githubusercontent.com/100833575/156916764-5c034b9e-c025-4bb2-83f2-f8eed586ee00.png">

**Comment by sdex** [comment]
Fixed in https://github.com/sdex/ActivityManager/pull/11
