### ISSUE TITLE
Intent Builder Feedback 

### ISSUE THREAD

**Issue by locuturus** [sdex/ActivityManager#42]
Hello, I have some quick thoughts about the intent builder (no particular order):

1. the mime type `vnd.android.document/directory` is missing from the list. It's hard to remember exactly how to type it manually.*
2. The intent silently sets `FLAG_ACTIVITY_PREVIOUS_IS_TOP` which isn't always wanted and AFAIK it can't be unset.
3. +1 for icon support #9
4. Thanks for creating it!

*I use that to create shortcuts to specific folders for the DocumentsUI Files app, I don't know how many other apps react to it but at least some file managers do.

**Comment by sdex** [comment]
I added this mime type (which is not a real mime type) to the list and an intent shortcut icons support in 5.4.0. 
Regarding the `FLAG_ACTIVITY_PREVIOUS_IS_TOP` flag, the app doesn't set it.
