### ISSUE TITLE
Data loss while using the app (dialog disappears on-screen rotation)

### ISSUE THREAD

**Issue by davirec** [sdex/ActivityManager#5]
When I perform these sequences of events, the dialog disappears on-screen rotation:
1. Go to the Main activity
2. Tap in Settings (gear button icon)
3. Tap in Theme
4. A fragment similar to this will appear:
Before rotation:
<img src="https://user-images.githubusercontent.com/3637419/158000757-f6780311-cbd9-45fd-b971-f8c505afdc48.png" width=30% height=30%>

5. Force the pause from the activity and then return to the activity (double rotation). Note that the fragment disappears and goes back to the main activity. 

Note: the pause from activity can be performed in several ways. We suggest using a double rotation (starts in portrait, goes to landscape, and back to portrait) with this function previously enabled in the smartphone.

The expected behavior is the return to the previous state with the fragments of the previous image.

However, the fragment disappears and goes back to the main activity.

After rotation:
<img src="https://user-images.githubusercontent.com/3637419/158000762-a4644287-a1bb-44e3-b5b0-5878d02470e9.png" width=30% height=30%>

Device:
- Device: Moto G30 with OS: Android 11
- Version: 4.1.4
- Device language: English

**Comment by sdex** [comment]
Fixed in https://github.com/sdex/ActivityManager/pull/12
