### ISSUE TITLE
Creating shortcut activity as root?

### ISSUE THREAD

**Issue by rubysm** [sdex/ActivityManager#56]
Launching activities as root is possible but creating shortcut of the activity as root? Is this feature intentionally avoided?

**Comment by sdex** [comment]
The app uses root to launch shortcuts for non-exported activities. 
Shortcuts for exported activities use intents.

**Comment by rubysm** [comment]
creating shortcut for (installed apps) in accessibility app requires root previlege, launching as root works but ain't works in
Shortcut.

**Comment by sdex** [comment]
It's a bug.

**Comment by rubysm** [comment]
Is this bug get fixed?

**Comment by sdex** [comment]
Yeah. I think I will add a checkbox to the shortcut screen to indicate that this shortcut must be launched using the root shell.

**Comment by sdex** [comment]
Added in [5.4.3](https://github.com/sdex/ActivityManager/releases/tag/5.4.3)

**Comment by rubysm** [comment]
Superb!.
