### ISSUE TITLE
[Feature Request] Use MaterialAlertDialogs when creating shortcuts

### ISSUE THREAD

**Issue by Jesse205** [sdex/ActivityManager#64]
This will make the UI more harmonious.

**Comment by sdex** [comment]
I didn't spend much time on it, but it seems like it won't be easy to implement because it's an activity with a dialog theme. 
Probably need to dig into MaterialAlertDialogBuilder.

**Comment by sdex** [comment]
Implemented in 360bcc992da036b99af5d730e19ae14b30da9be0

**Comment by Jesse205** [comment]
Thank you.
