### ISSUE TITLE
Data loss on double screen rotation

### ISSUE THREAD

**Issue by davirec** [sdex/ActivityManager#7]
Hi, this issue has a relation with #5.

We found failures similar in activities:

- ActivitiesListActivity: menu bar changed, screen text disappears, various properties disappear

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159147198-2738482a-bc45-4dc4-a411-6a315f41d02b.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159147196-e9a2ff06-6641-49d7-8f7c-d30182fb4543.png" width=20% height=20%>
</figure>

</div> 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159147214-b8130d8b-2941-49cd-982a-5d9eef0a9ce1.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159147213-672f61d2-8760-437b-9475-67cf79ed1143.png" width=20% height=20%>
</figure>

</div> 

- AddShortcutDialogActivity: changed menu bar

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159147396-b99582ff-1b75-414d-b57a-7eaec6331bf8.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159147395-5592494d-5a43-4d69-b89d-d505b9f3292f.png" width=20% height=20%>
</figure>

</div> 

- MainActivity: changed menu bar

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159147377-ce6c3cc9-d9be-486c-b3c4-f068de648dfc.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159147376-2d70af39-3c78-4fd2-8de3-01a079e1abf6.png" width=20% height=20%>
</figure>

</div> 

- ManifestViewerActivity: returned to previous activity, several properties disappear

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159147423-4ca08b48-e24a-4520-8e95-389fa93edbd6.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159147421-78b42127-1e91-4eae-9caf-53668bcb1b59.png" width=20% height=20%>
</figure>

</div> 

Note:

- Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
- A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.

**Comment by sdex** [comment]
Most of the issues have been fixed already. Existing ones aren't important.
