### ISSUE TITLE
[Feature request] Add translation links within the About page

### ISSUE THREAD

**Issue by Jesse205** [sdex/ActivityManager#76]
This does not need to enter github to translate applications, especially for some areas that may not be able to access github very friendly.

**Comment by sdex** [comment]
I added the link to the crowdin along with others.

![Screenshot_20240209_100647](https://github.com/sdex/ActivityManager/assets/3196011/4a47db75-63fd-46f4-8973-b99a078a2746)

**Comment by Jesse205** [comment]
Thank you!
