### ISSUE TITLE
Support `setData()`

### ISSUE THREAD

**Issue by opk12** [sdex/ActivityManager#8]
I want to work around a Matrix Element bug in making shortcuts; I want to choose a custom icon for a shortcut to Firefox Fennec.

I can do both with this app, if it lets me `setData()` to a custom URI.

```
// im.vector.app.features.link.LinkHandlerActivity - mozilla.components.feature.pwa.WebAppLauncherActivity
Intent intent = new Intent();
intent.setClassName(packageName, activityName);
intent.setData(android.net.Uri.parse(permalink));
ctx.startActivity(intent);
```

**Comment by sdex** [comment]
You can create any `intent` set `data` field to whatever you want.  

![photo1650005330](https://user-images.githubusercontent.com/3196011/163532856-348658d5-80e1-4e1a-8cea-610b66265c1b.jpeg)

**Comment by opk12** [comment]
How to reach that window? On 4.1.4 I have the same screens as [here](https://f-droid.org/de/packages/com.activitymanager/#screenshots) and the dialog `Edit shortcut` only has the icon and label.

**Comment by sdex** [comment]
You need to open `Activity Manager` in `Activity Manager`, then launch `IntentBuilderActivity`, create the custom intent and launch it. From the history you can create a shortcut for the intent. 
![photo1650015430](https://user-images.githubusercontent.com/3196011/163555091-b9071d4b-3ecc-4822-998e-15dc4f6b47f2.jpeg)

**Comment by opk12** [comment]
For myself: the history is `HistoryActivity` and is at the top-right in the `Intent launcher` activity.

**Comment by opk12** [comment]
Many thanks. I have not found even a very brief mention in-app, is there a specific reason?

**Comment by sdex** [comment]
This was not a very popular feature and I decided to not support it anymore but didn't want to remove it from the app. 
It's neither mentioned in the UI nor documented, but it reflects android API for the Intent, so any android developer can easily use it.
