### ISSUE TITLE
Shizuku 

### ISSUE THREAD

**Issue by w1s3one805** [sdex/ActivityManager#85]
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh echo start

**Comment by w1s3one805** [comment]
> adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh echo start 

Outlook Mail

**Comment by shugen002** [comment]
Hi! I want to know why this issue was closed.
